scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: django
    scrape_interval: 10s
    static_configs:
      - targets:
          - "ecs.web:8000"
  - job_name: database
    scrape_interval: 10s
    static_configs:
      - targets:
          - "database-exporter:9187"
  - job_name: node
    scrape_interval: 10s
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: redis_exporter
    scrape_interval: 10s
    static_configs:
      - targets:
        - "redis-exporter:9121"